print ("")
print ("\033[93m                                                                 .__            ")
print ("\033[92m                                                 ____   _____    |  |     ____  ")
print ("\033[91m                                               _/ ___\  \__  \   |  |   _/ ___\ ")
print ("\033[94m                                               \  \___   / __ \_ |  |__ \  \___ ")
print ("\033[95m                                                \___  > (____  / |____/  \___  >")
print ("\033[34m                                                    \/       \/              \/ ")
print ("\033[33m                                                                    (09-10-20)  ")
print ("")
while True:
 plus = str(input("\033[96m  SILAHKAN PILIH [+ / - / : / x / ** / 0 ] : "))
 if plus == "+":
  print ("")
  print ("  PENJUMLAHAN")
#  print ("                                                        ._")
#  print ("                                               ______   |  |    __ __    ______")
#  print ("                                               \____ \  |  |   |  |  \  /  ___/")
#  print ("                                               |  |_> > |  |__ |  |  /  \___ \ ")
#  print ("                                               |   __/  |____/ |____/  /____  >")
#  print ("                                               |__|                         \/ ")
  print ("")
  tambah=int(input("  MASUKKAN ANGKA\033[33m :\033[0m "))
  tambah1=int(input("                   + \n                   "))
  print ("                \033[33m   ------------------------------- =\n \033[91m                 ", tambah + tambah1)
  print ("")
 elif plus == "-":
  print ("")
  print ("  PENGURANGAN")
#  print ("                                                         .__")
#  print ("                                                 _____   |__|   ____    __ __    ______")
#  print ("                                                /     \  |  |  /    \  |  |  \  /  ___/")
#  print ("                                               |  Y Y  \ |  | |   |  \ |  |  /  \___ \ ")
#  print ("                                               |__|_|  / |__| |___|  / |____/  /____  >")
#  print ("                                                     \/            \/               \/ ")
  print ("")
  kurang=int(input("  MASUKKAN ANGKA\033[33m :\033[0m "))
  kurang1=int(input("                   - \n                   "))
  print ("                 \033[33m  ------------------------------- =\n \033[91m                 ", kurang - kurang1)
  print ("")
 elif plus == "x":
  print ("")
  print ("  PENGALIAN")
  print ("")
  kali=int(input("  MASUKKAN ANGKA\033[33m :\033[0m "))
  kali1=int(input("                 \033[33m  x \n                   "))
  print ("                \033[33m   ------------------------------- =\n \033[91m                 ", kali * kali1)
  print ("")
 elif plus == ":":
  print ("")
  print ("  PEMBAGIAN")
  print ("")
  bagi=int(input("  MASUKKAN ANGKA\033[33m :\033[0m "))
  bagi1=int(input("                  \033[33m :\033[0m \n                   "))
  print ("                 \033[33m  ------------------------------- =\n \033[91m                 ", bagi / bagi1)
  print ("")
 elif plus == "**":
  print ("")
  print ("  PERPANGKARAN")
  print ("")
  pang=int(input("  MASUKKAN ANGKA\033[33m :\033[0m "))
  pang1=int(input("                  \033[33m **\033[0m \n                   "))
  print ("                 \033[33m  ------------------------------- =\n \033[91m                 ", pang ** pang1)
  print ("")
 elif plus == "0":
  print ("")
  print ("         exit boss...")
  print ("")
  exit()
 else:
  print ("")
  print (" \033[91m NGGA ADAAAA !!!!")
  print ("")
else:
 print ("done")
